export const APIURL=`http://course-data.mark2win.com/solo?mykey=R7TpiCsen9aLm4HN%2BUHDHGRN4VOpa%2BZzZjH7Z0yZLCoMBMh3Ih/r4NTX3MyERdMZu/jA3IMlkNoqJw3Ee668cA==`
export const actionType={
    ALL_SONGS:'ALL-SONGS', 
SELECT_SONGS:'SELECT_SONGS', 
FAV_SONGS:'FAV_SONGS',
PAUSE_SONGS:'PAUSE_SONGS',
PLAY_SONGS:'PLAY_SONGS',
RANDOM_SONGS:'RANDOM_SONGS',
SEARCH_SONGS:'SEARCH_SONGS',
SHOW_FAVLIST:'SHOW_FAVLIST'
}